### ISSUE TITLE
Temprature threshold on clothes a tad bit extreme.

### ISSUE THREAD

**Issue by Katnjia** [jecrell/Call-of-Cthulhu---Factions#1]
https://share.riseup.net/#TSeqQl9p2YkRK0q2f_G2tg
https://share.riseup.net/#zpgg-g_Ow-ZW_glBLOr1tg

Hey'a. This seems to only affected by clothing from the Factions mod. I have a pretty good crafter, but no one is so good that they can make a fur coat stand -132.8*C just from Alpaca wool.

Disclaimer: I do have other mods loaded as well.

**Comment by jecrell** [comment]
Seems to have been resolved. Closing for now.
